apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "project-fyr.watcherName" . }}
  labels:
    {{- include "project-fyr.labels" . | nindent 4 }}
    app.kubernetes.io/name: project-fyr
    app.kubernetes.io/component: watcher
spec:
  replicas: {{ .Values.watcher.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: watcher
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/component: watcher
        app.kubernetes.io/name: project-fyr
    spec:
      serviceAccountName: {{ default (printf "%s-sa" .Release.Name) .Values.serviceAccount.name }}
      containers:
        - name: watcher
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- with .Values.watcher.command }}
          command:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.watcher.args }}
          args:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          envFrom:
            - configMapRef:
                name: {{ include "project-fyr.fullname" . }}
          volumeMounts:
            - name: data
              mountPath: /data
          resources:
            {{- toYaml .Values.watcher.resources | nindent 12 }}
      volumes:
        - name: data
          emptyDir: {}
      {{- with .Values.watcher.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.watcher.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.watcher.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
