{{- if .Values.gitlabIngestor.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "project-fyr.gitlabName" . }}
  labels:
    {{- include "project-fyr.labels" . | nindent 4 }}
    app.kubernetes.io/name: project-fyr
    app.kubernetes.io/component: gitlab-ingestor
spec:
  type: {{ .Values.gitlabIngestor.service.type }}
  ports:
    - name: http
      port: {{ .Values.gitlabIngestor.service.port }}
      targetPort: http
  selector:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: gitlab-ingestor
{{- end }}
