{{- if .Values.gitlabIngestor.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "project-fyr.gitlabName" . }}
  labels:
    {{- include "project-fyr.labels" . | nindent 4 }}
    app.kubernetes.io/name: project-fyr
    app.kubernetes.io/component: gitlab-ingestor
spec:
  replicas: {{ .Values.gitlabIngestor.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: gitlab-ingestor
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/component: gitlab-ingestor
        app.kubernetes.io/name: project-fyr
    spec:
      containers:
        - name: gitlab-ingestor
          image: "{{ default .Values.image.repository .Values.gitlabIngestor.image.repository }}:{{ default .Values.image.tag .Values.gitlabIngestor.image.tag }}"
          imagePullPolicy: {{ default .Values.image.pullPolicy .Values.gitlabIngestor.image.pullPolicy }}
          {{- with .Values.gitlabIngestor.command }}
          command:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.gitlabIngestor.args }}
          args:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          envFrom:
            - configMapRef:
                name: {{ include "project-fyr.fullname" . }}
          ports:
            - name: http
              containerPort: {{ .Values.gitlabIngestor.service.port }}
          resources:
            {{- toYaml .Values.gitlabIngestor.resources | nindent 12 }}
      {{- with .Values.gitlabIngestor.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.gitlabIngestor.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.gitlabIngestor.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
