{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ default (printf "%s-sa" .Release.Name) .Values.serviceAccount.name }}
  labels:
    {{- include "project-fyr.labels" . | nindent 4 }}
    app.kubernetes.io/name: project-fyr
    app.kubernetes.io/component: watcher
{{- end }}
