{{- if .Values.slackMock.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "project-fyr.fullname" . }}-slack-mock
  labels:
    {{- include "project-fyr.labels" . | nindent 4 }}
    app.kubernetes.io/component: slack-mock
spec:
  type: {{ .Values.slackMock.service.type }}
  ports:
  - port: {{ .Values.slackMock.service.port }}
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: slack-mock
{{- end }}
